Done the third challenge, waiting for approve and ready to merge
Lye-Frozen-Heart/JavaScript-foundations-challenge-1 pull request #3
Opened 2023-11-03 17:36 UTC by Lye-Frozen-Heart

2023-11-05 20:17 UTC, tictools requested changes

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/README.md
⚠️ FIX: move `READEM.md` at project root level

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
> +if (animal == "cat") console.log("Meow!");
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +if (numberToCheck % 2 == 0)
Even it is not necessary, it very recommended to use brackets when using if/else statement

```suggestion
if (...){
  //...
} else {
  //...
}
```

⚠️ FIX: format `if/else` statement

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let i = 10; i <= 40; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +/**
A better solution...

```js
for (let i = 10; i <= 40; i++) {
  if (i % 2 === 0) console.log("Pair: ", i);
  if (i % 2 !== 0) console.log("Odd: ", i);
}
```

Take care of comparision operators. It's not the same using the equality operator (`==`) than usinng the strict equality operator (`===`).
Strict equality operator i sthe most recommende for most of the cases we will manage.

* [equality operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality)
* [strict equality operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality)

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +for (let i = 0; i <= 10; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i < 100; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_00.js
> +let i = 0;
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 20:17 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +let incremental = 10;
⚠️ FIX: remove commented code

2023-11-06 16:18 UTC, Lye-Frozen-Heart commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +/**
Yeah I know it is not the same. The strict one also checks if the operands are from the same type, so I ensured that the checked number is always a number not a string or any other type. Even so for this basic exercise maybe it's not necessary.

2023-11-13 18:22 UTC, nilete22 approved these changes

2023-11-13 19:25 UTC, merged